// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userserver.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequ struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string   `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequ) Reset()         { *m = RegisterRequ{} }
func (m *RegisterRequ) String() string { return proto.CompactTextString(m) }
func (*RegisterRequ) ProtoMessage()    {}
func (*RegisterRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ca2ed8dfbcdaf7e, []int{0}
}

func (m *RegisterRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequ.Unmarshal(m, b)
}
func (m *RegisterRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequ.Marshal(b, m, deterministic)
}
func (m *RegisterRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequ.Merge(m, src)
}
func (m *RegisterRequ) XXX_Size() int {
	return xxx_messageInfo_RegisterRequ.Size(m)
}
func (m *RegisterRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequ.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequ proto.InternalMessageInfo

func (m *RegisterRequ) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequ) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type RegisterResp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ca2ed8dfbcdaf7e, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserRequ struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequ) Reset()         { *m = GetUserRequ{} }
func (m *GetUserRequ) String() string { return proto.CompactTextString(m) }
func (*GetUserRequ) ProtoMessage()    {}
func (*GetUserRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ca2ed8dfbcdaf7e, []int{2}
}

func (m *GetUserRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequ.Unmarshal(m, b)
}
func (m *GetUserRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequ.Marshal(b, m, deterministic)
}
func (m *GetUserRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequ.Merge(m, src)
}
func (m *GetUserRequ) XXX_Size() int {
	return xxx_messageInfo_GetUserRequ.Size(m)
}
func (m *GetUserRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequ proto.InternalMessageInfo

func (m *GetUserRequ) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResp struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string   `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ca2ed8dfbcdaf7e, []int{3}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserResp) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *GetUserResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequ)(nil), "proto.RegisterRequ")
	proto.RegisterType((*RegisterResp)(nil), "proto.RegisterResp")
	proto.RegisterType((*GetUserRequ)(nil), "proto.GetUserRequ")
	proto.RegisterType((*GetUserResp)(nil), "proto.GetUserResp")
}

func init() {
	proto.RegisterFile("userserver.proto", fileDescriptor_4ca2ed8dfbcdaf7e)
}

var fileDescriptor_4ca2ed8dfbcdaf7e = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x2a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x4a, 0x1e, 0x5c, 0x3c, 0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0xa5,
	0x42, 0x52, 0x5c, 0x1c, 0x20, 0xa5, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x70, 0xbe, 0x90, 0x0c, 0x17, 0x27, 0x88, 0xed, 0x9a, 0x9b, 0x98, 0x99, 0x23, 0xc1, 0x04,
	0x96, 0x44, 0x08, 0x28, 0xa9, 0x21, 0x9b, 0x54, 0x5c, 0x20, 0x24, 0xc6, 0xc5, 0x06, 0x92, 0xf4,
	0x4c, 0x01, 0x9b, 0xc3, 0x1c, 0x04, 0xe5, 0x29, 0xa9, 0x72, 0x71, 0xbb, 0xa7, 0x96, 0x84, 0x16,
	0x43, 0x2d, 0xc4, 0xa5, 0x2c, 0x1e, 0x49, 0x59, 0x71, 0x01, 0xf9, 0xee, 0x42, 0xb2, 0x80, 0x19,
	0xd9, 0x02, 0xa3, 0x4a, 0x2e, 0x2e, 0x90, 0xe9, 0xc1, 0xe0, 0x40, 0x11, 0x32, 0xe3, 0xe2, 0x80,
	0xb9, 0x5e, 0x48, 0x18, 0x12, 0x44, 0x7a, 0xc8, 0x01, 0x23, 0x85, 0x29, 0x58, 0x5c, 0xa0, 0xc4,
	0x20, 0x64, 0xcc, 0xc5, 0x0e, 0x75, 0xa6, 0x90, 0x10, 0x54, 0x05, 0x92, 0xef, 0xa4, 0x30, 0xc4,
	0x40, 0x9a, 0x92, 0xd8, 0xc0, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0xaf, 0x71,
	0x3a, 0x96, 0x01, 0x00, 0x00,
}
