// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userserver.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServer service

type UserServerService interface {
	Register(ctx context.Context, in *RegisterRequ, opts ...client.CallOption) (*RegisterResp, error)
	GetUser(ctx context.Context, in *GetUserRequ, opts ...client.CallOption) (*GetUserResp, error)
}

type userServerService struct {
	c    client.Client
	name string
}

func NewUserServerService(name string, c client.Client) UserServerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &userServerService{
		c:    c,
		name: name,
	}
}

func (c *userServerService) Register(ctx context.Context, in *RegisterRequ, opts ...client.CallOption) (*RegisterResp, error) {
	req := c.c.NewRequest(c.name, "UserServer.Register", in)
	out := new(RegisterResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServerService) GetUser(ctx context.Context, in *GetUserRequ, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "UserServer.GetUser", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServer service

type UserServerHandler interface {
	Register(context.Context, *RegisterRequ, *RegisterResp) error
	GetUser(context.Context, *GetUserRequ, *GetUserResp) error
}

func RegisterUserServerHandler(s server.Server, hdlr UserServerHandler, opts ...server.HandlerOption) error {
	type userServer interface {
		Register(ctx context.Context, in *RegisterRequ, out *RegisterResp) error
		GetUser(ctx context.Context, in *GetUserRequ, out *GetUserResp) error
	}
	type UserServer struct {
		userServer
	}
	h := &userServerHandler{hdlr}
	return s.Handle(s.NewHandler(&UserServer{h}, opts...))
}

type userServerHandler struct {
	UserServerHandler
}

func (h *userServerHandler) Register(ctx context.Context, in *RegisterRequ, out *RegisterResp) error {
	return h.UserServerHandler.Register(ctx, in, out)
}

func (h *userServerHandler) GetUser(ctx context.Context, in *GetUserRequ, out *GetUserResp) error {
	return h.UserServerHandler.GetUser(ctx, in, out)
}
